export const UNIVERSITY_OPTIONS = [
  'Harvard University',
  'Stanford University',
  'Massachusetts Institute of Technology',
  'University of Oxford',
  'University of Cambridge',
  'California Institute of Technology',
  'ETH Zurich',
  'Imperial College London',
  'University College London',
  'University of Chicago',
  'Yale University',
  'Princeton University',
  'Columbia University',
  'University of Pennsylvania',
  'Cornell University',
  'Northwestern University',
  'Duke University',
  'University of Michigan',
  'University of California, Berkeley',
  'University of California, Los Angeles',
  'University of Toronto',
  'McGill University',
  'University of British Columbia',
  'National University of Singapore',
  'Nanyang Technological University',
  'University of Melbourne',
  'Australian National University',
  'University of Sydney',
  'University of New South Wales',
  'Tsinghua University',
  'Peking University',
  'Fudan University',
  'University of Tokyo',
  'Kyoto University',
  'Seoul National University',
  'KAIST',
  'Hong Kong University of Science and Technology',
  'University of Hong Kong',
  'Bocconi University',
  'HEC Paris',
  'INSEAD',
  'London Business School',
  'IE Business School',
  'IESE Business School',
  'ESADE',
  'Indian Institute of Management Ahmedabad',
  'Indian Institute of Management Bangalore',
  'Indian School of Business',
  'University of Cape Town',
  'University of Amsterdam',
  'Other (type your own)'
];

export const DEGREE_OPTIONS = [
  'MBA',
  'Master in Management',
  'MS Computer Science',
  'MS Data Science',
  'MS Finance',
  'Master of Public Policy',
  'Master of Public Health',
  'Master of Engineering Management',
  'Master in Marketing',
  'Other'
];

export const DOC_TEMPLATES = [
  { id: 'resume', label: 'Resume / CV' },
  { id: 'transcripts', label: 'Academic Transcripts' },
  { id: 'test_scores', label: 'Test Scores (GMAT/GRE/TOEFL/IELTS)' },
  { id: 'recommender_list', label: 'Recommender Contact Sheet' },
  { id: 'sop_notes', label: 'Statement of Purpose Notes' },
  { id: 'financial_docs', label: 'Financial Proof / Funding Docs' }
];
