import { createNotificationActions } from '../notificationActions';
import { createNavigationActions } from '../navigationActions';
import { createProfileActions } from '../profileActions';
import { createEssayApplicationActions } from '../essayApplicationActions';

export function useAppActions({
  DEGREE_OPTIONS,
  getVersionIdentity,
  applications,
  selectedApplicationId,
  selectedEssay,
  confirmDelete,
  editingApplicationId,
  essayDegreeChoice,
  essayCustomDegree,
  applicationDegreeChoice,
  applicationCustomDegree,
  formData,
  applicationFormData,
  setEssays,
  setApplications,
  setVersions,
  setVersionDiffSelection,
  setShowVersions,
  setLoading,
  setFormData,
  setEssayDegreeChoice,
  setEssayCustomDegree,
  setShowForm,
  setSelectedEssay,
  setReview,
  setApplicationFormData,
  setApplicationDegreeChoice,
  setApplicationCustomDegree,
  setEditingApplicationId,
  setShowApplicationForm,
  setActiveNav,
  setApplicationLoading,
  setSelectedApplicationId,
  setDismissedNotifications,
  setIsProfileMenuOpen,
  setExpandedNavGroups,
  setDocsApplicationId,
  setApplicationSearch,
  globalSearch,
  updateProfile,
  profileFormData,
  user,
  setProfileFormData,
  profileMessage,
  setProfileMessage,
  setProfileSaving,
  setReminderLoading,
  setReminderPreview,
  setReminderSending,
  setEssayDraftRecovered,
  setApplicationDraftRecovered,
  feedbackCategory,
  feedbackMessage,
  activeNav,
  setFeedbackCategory,
  setFeedbackMessage,
  setFeedbackSending,
  setFeedbackStatus
}) {
  const essayApplicationActions = createEssayApplicationActions({
    degreeOptions: DEGREE_OPTIONS,
    getVersionIdentity,
    applications,
    selectedApplicationId,
    selectedEssay,
    confirmDelete,
    editingApplicationId,
    essayDegreeChoice,
    essayCustomDegree,
    applicationDegreeChoice,
    applicationCustomDegree,
    formData,
    applicationFormData,
    setEssays,
    setApplications,
    setVersions,
    setVersionDiffSelection,
    setShowVersions,
    setLoading,
    setFormData,
    setEssayDegreeChoice,
    setEssayCustomDegree,
    setShowForm,
    setSelectedEssay,
    setReview,
    setApplicationFormData,
    setApplicationDegreeChoice,
    setApplicationCustomDegree,
    setEditingApplicationId,
    setShowApplicationForm,
    setActiveNav,
    setApplicationLoading,
    setSelectedApplicationId,
    setEssayDraftRecovered,
    setApplicationDraftRecovered
  });

  const notificationActions = createNotificationActions({
    setDismissedNotifications
  });

  const navigationActions = createNavigationActions({
    setIsProfileMenuOpen,
    setActiveNav,
    handleOpenNewEssayForm: essayApplicationActions.handleOpenNewEssayForm,
    setShowForm,
    setShowApplicationForm,
    setEditingApplicationId,
    setSelectedEssay,
    setReview,
    setShowVersions,
    setDocsApplicationId,
    selectedApplicationId,
    setExpandedNavGroups,
    setSelectedApplicationId,
    applications,
    setApplicationSearch,
    globalSearch
  });

  const profileActions = createProfileActions({
    updateProfile,
    profileFormData,
    user,
    setProfileFormData,
    profileMessage,
    setProfileMessage,
    setProfileSaving,
    setReminderLoading,
    setReminderPreview,
    setReminderSending,
    feedbackCategory,
    feedbackMessage,
    activeNav,
    setFeedbackCategory,
    setFeedbackMessage,
    setFeedbackSending,
    setFeedbackStatus
  });

  return {
    ...essayApplicationActions,
    ...notificationActions,
    ...navigationActions,
    ...profileActions
  };
}
